#!/usr/bin/env python3
"""
Email notification wrapper using Gmail OAuth2.
Usage: python tools/slack.py "<message>"

Auth priority:
  1. token.json in project root (local runs — generated by tools/setup_gmail_auth.py)
  2. GMAIL_TOKEN_B64 env var (cloud runs — base64-encoded token.json)
  3. Falls back to DAILY-SUMMARY.md if neither is available
"""
import base64
import json
import os
import sys
import warnings
from datetime import datetime
from email.mime.text import MIMEText
from pathlib import Path

warnings.filterwarnings("ignore")

ROOT = Path(__file__).parent.parent

# Load .env if present
env_file = ROOT / ".env"
if env_file.exists():
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, val = line.partition("=")
            os.environ.setdefault(key.strip(), val.strip())

if len(sys.argv) < 2 or not sys.argv[1].strip():
    print('Usage: python tools/slack.py "<message>"', file=sys.stderr)
    sys.exit(1)

msg_text = sys.argv[1]
email_from = os.environ.get("NOTIFY_EMAIL_FROM", "jamesonjeancharles2935@gmail.com")
email_to = os.environ.get("NOTIFY_EMAIL_TO", "jamesonjeancharles2935@gmail.com")
stamp = datetime.now().strftime("%Y-%m-%d %H:%M")


def _fallback():
    fallback = ROOT / "DAILY-SUMMARY.md"
    with fallback.open("a") as f:
        f.write(f"\n---\n## {stamp} (fallback — Gmail not configured)\n{msg_text}\n")
    print("[notify fallback] appended to DAILY-SUMMARY.md")
    print(msg_text)


def _send(creds):
    from googleapiclient.discovery import build
    subject = f"Trading Bot — {stamp}"
    msg = MIMEText(msg_text, "plain")
    msg["Subject"] = subject
    msg["From"] = email_from
    msg["To"] = email_to
    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    service = build("gmail", "v1", credentials=creds)
    service.users().messages().send(userId="me", body={"raw": raw}).execute()
    print(f"[notify] email sent to {email_to}")


try:
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request
except ImportError:
    print("WARNING: google-auth not installed — falling back to file", file=sys.stderr)
    _fallback()
    sys.exit(0)

# Try token.json (local)
token_file = ROOT / "token.json"
creds = None

if token_file.exists():
    creds = Credentials.from_authorized_user_file(str(token_file))

# Try GMAIL_TOKEN_B64 (cloud routine env var)
elif os.environ.get("GMAIL_TOKEN_B64"):
    token_json = base64.b64decode(os.environ["GMAIL_TOKEN_B64"]).decode()
    creds = Credentials.from_authorized_user_info(json.loads(token_json))

if creds is None:
    _fallback()
    sys.exit(0)

# Refresh if expired
if not creds.valid:
    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
        if token_file.exists():
            token_file.write_text(creds.to_json())
    else:
        _fallback()
        sys.exit(0)

try:
    _send(creds)
except Exception as e:
    print(f"WARNING: email failed ({e}) — falling back to file", file=sys.stderr)
    _fallback()
